// Responsável por definir o kit de combate do default_champion a partir do base compartilhado.
import { createCombatAction, createCombatKit } from "../combat-kit.utils.js";
import { BASE_HUMANOID_BASIC_ATTACKS, BASE_HUMANOID_COMBAT_KIT } from "../combat-definition.js";
import type { CombatKitDefinition } from "../combat-types.js";

const DEFAULT_CHAMPION_BASIC_ATTACKS: CombatKitDefinition["basicAttacks"] = [
  createCombatAction(BASE_HUMANOID_BASIC_ATTACKS[0], {
    id: "default_champion.basic.1",
    animationCommand: "attack1"
  }),
  createCombatAction(BASE_HUMANOID_BASIC_ATTACKS[1], {
    id: "default_champion.basic.2",
    animationCommand: "attack2"
  }),
  createCombatAction(BASE_HUMANOID_BASIC_ATTACKS[2], {
    id: "default_champion.basic.3",
    animationCommand: "attack3"
  })
];

export const DEFAULT_CHAMPION_COMBAT_KIT: CombatKitDefinition = createCombatKit(
  BASE_HUMANOID_COMBAT_KIT,
  {
    basicAttacks: DEFAULT_CHAMPION_BASIC_ATTACKS,
    skillsBySlot: {
      1: {
        id: "default_champion.skill.fireball",
        kind: "skill",
        sourceType: "skill",
        animationCommand: "fireball",
        skillSlot: 1,
        skillId: "fireball",
        damage: 95,
        range: 12,
        angleDegrees: 18,
        radius: 0.6,
        knockback: 0.35,
        hitstunMs: 180,
        windupMs: 220,
        activeMs: 120,
        recoveryMs: 260,
        comboQueueWindowMs: 0,
        cooldownMs: 4200,
        interruptible: true,
        canQueueNextAttack: false,
        canBeInterrupted: true,
        movementLock: "partial",
        targetingShape: "projectile_line",
        isBlockable: false,
        hitBursts: [{ offsetMs: 0 }],
        vfxHook: "fireball_cast",
        sfxHook: "fireball_cast"
      },
      2: {
        id: "default_champion.skill.kick_skill",
        kind: "skill",
        sourceType: "skill",
        animationCommand: "kickSkill",
        skillSlot: 2,
        skillId: "kick-skill",
        damage: 120,
        range: 3,
        angleDegrees: 84,
        radius: 1.05,
        knockback: 1.05,
        hitstunMs: 260,
        windupMs: 180,
        activeMs: 160,
        recoveryMs: 280,
        comboQueueWindowMs: 0,
        cooldownMs: 6000,
        interruptible: true,
        canQueueNextAttack: false,
        canBeInterrupted: true,
        movementLock: "full",
        targetingShape: "melee_cone",
        isBlockable: true,
        hitBursts: [{ offsetMs: 0 }],
        vfxHook: "kick_skill",
        sfxHook: "kick_skill"
      },
      3: {
        id: "default_champion.skill.repeat_kick",
        kind: "skill",
        sourceType: "skill",
        animationCommand: "repeatKick",
        skillSlot: 3,
        skillId: "reapet-kick",
        damage: 60,
        range: 2.8,
        angleDegrees: 88,
        radius: 1.05,
        knockback: 0.48,
        hitstunMs: 120,
        windupMs: 160,
        activeMs: 360,
        recoveryMs: 280,
        comboQueueWindowMs: 0,
        cooldownMs: 7600,
        interruptible: false,
        canQueueNextAttack: false,
        canBeInterrupted: false,
        movementLock: "full",
        targetingShape: "melee_cone",
        isBlockable: true,
        hitBursts: [{ offsetMs: 0 }, { offsetMs: 120 }, { offsetMs: 240 }],
        vfxHook: "repeat_kick",
        sfxHook: "repeat_kick"
      },
      4: {
        id: "default_champion.skill.spell",
        kind: "skill",
        sourceType: "skill",
        animationCommand: "spell",
        skillSlot: 4,
        skillId: "spell",
        damage: 110,
        range: 7.5,
        angleDegrees: 48,
        radius: 2.4,
        knockback: 0.4,
        hitstunMs: 220,
        windupMs: 260,
        activeMs: 120,
        recoveryMs: 320,
        comboQueueWindowMs: 0,
        cooldownMs: 9000,
        interruptible: true,
        canQueueNextAttack: false,
        canBeInterrupted: true,
        movementLock: "partial",
        targetingShape: "self_aoe",
        isBlockable: false,
        hitBursts: [{ offsetMs: 0 }],
        vfxHook: "spell_burst",
        sfxHook: "spell_burst"
      },
      5: {
        id: "default_champion.skill.ultimate",
        kind: "skill",
        sourceType: "ultimate",
        animationCommand: "ultimate",
        skillSlot: 5,
        skillId: "ultimate",
        damage: 220,
        range: 8.5,
        angleDegrees: 360,
        radius: 4.5,
        knockback: 1.4,
        hitstunMs: 540,
        windupMs: 500,
        activeMs: 220,
        recoveryMs: 540,
        comboQueueWindowMs: 0,
        cooldownMs: 18000,
        interruptible: false,
        canQueueNextAttack: false,
        canBeInterrupted: false,
        movementLock: "full",
        targetingShape: "self_aoe",
        isBlockable: false,
        hitBursts: [{ offsetMs: 0 }],
        vfxHook: "default_ultimate",
        sfxHook: "default_ultimate",
        ultimateChargeCost: 100
      }
    }
  }
);
